// This is Azure Resource Graph Explorer query
// List all azure public IP addressess
resources
| where type == "microsoft.network/publicipaddresses"
| mv-expand todynamic(properties)
| where isnotempty(properties.ipAddress)
| extend AzurePublicIP = tostring(properties.ipAddress)
| project ['id'], name, location, resourceGroup, subscriptionId, properties.ipAddress, AzurePublicIP, ['tags']
//| summarize count(AzurePublicIP) 
//| summarize count() by AzurePublicIP 
//| distinct AzurePublicIP
